'use strict';
(()=>{
const q=s=>document.querySelector(s),M=window.DinoMath;
const objectives={dino:['서로 다른 시야, 일관된 전체 표현','교사의 CLS를 헤드에 통과시켜 만든 목표 분포와 학생의 분포 사이 교차엔트로피를 줄입니다. 같은 이미지의 다른 crop을 연결하는 것이지, 라벨을 보고 같은 클래스의 사진을 직접 묶는 지도학습이 아닙니다.'],ibot:['가려진 부분의 잠재 의미를 예측','학생에게 일부 패치를 가리고, 교사가 가리지 않은 입력에서 만든 해당 위치의 목표 분포를 맞추게 합니다. 픽셀의 RGB 값을 복원하는 문제가 아니라, 특징 공간에서 학습하는 masked image modeling입니다.'],koleo:['모든 점이 한곳에 몰리지 않도록','배치의 정규화된 CLS 특징에서 최근접 이웃 거리가 지나치게 작아지는 것을 억제합니다. 표현을 더 고르게 퍼뜨리는 보조 목표이며, 클래스별 간격이나 의미 있는 경계를 직접 보장하는 규칙은 아닙니다.'],gram:['전체를 배우면서 부분의 관계도 보존','별도 Gram 교사의 패치 유사도 행렬을 참조합니다. 일반 EMA 교사와 역할이 다릅니다. 대규모 교사 정제 단계에 쓰이며, 고정된 7B에서 작은 모델로 증류할 때는 논문에서 Gram anchoring을 적용하지 않습니다.']};
function setObjective(key){if(!objectives[key])throw Error('Unknown objective');document.querySelectorAll('[data-objective]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.objective===key)));q('#objectiveText').innerHTML=`<h3>${objectives[key][0]}</h3><p>${objectives[key][1]}</p>`}
document.querySelectorAll('[data-objective]').forEach(b=>b.onclick=()=>setObjective(b.dataset.objective));setObjective('dino');
const tokenText={cls:'CLS는 이미지 전체를 요약하는 학습된 토큰입니다. ViT-L에서는 1,024차원의 이미지 표현을 얻습니다.',reg:'Register 4개는 계산을 위한 보조 저장 공간입니다. 특정 픽셀 위치에 대응하지 않으며, 일반적인 이미지 검색 벡터로 그대로 사용하지 않습니다.',patch:'각 패치 토큰은 해당 위치를 중심으로 전체 문맥까지 반영합니다. 분할·대응점 탐색 같은 위치별 작업에 활용할 수 있습니다.'};
document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-token]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));q('#tokenDescription').textContent=tokenText[b.dataset.token]});
function updateTokens(){
 const res=Number(q('#resolution').value),c=M.tokenCounts(res),n=res/16;
 let cells='';for(let y=0;y<n;y++)for(let x=0;x<n;x++)cells+=`<rect x="${x*256/n}" y="${y*256/n}" width="${256/n-.6}" height="${256/n-.6}" fill="${(x+y)%4===0?'#F86825':'#DBDCDF'}"/>`;
 q('#patchGrid').innerHTML=cells;q('#patchCount').textContent=c.patches.toLocaleString();q('#totalTokens').textContent=c.tokens.toLocaleString();q('#stripCount').textContent=c.patches;
 const mobile=innerWidth<=650,viewWidth=mobile?360:600,maxWidth=mobile?207:365,font=mobile?14:16;
 q('#costChart').setAttribute('viewBox',`0 0 ${viewWidth} 215`);
 let svg='';[224,256,512,768].forEach((r,i)=>{const k=M.tokenCounts(r),y=20+i*45,width=k.pairs/M.tokenCounts(768).pairs*maxWidth;svg+=`<text x="0" y="${y+17}" fill="#585858" font-size="${font}">${r}px</text><rect x="60" y="${y}" width="${Math.max(width,3)}" height="24" fill="${r===res?'#F86825':'#C2C4C8'}"/><text x="${70+width}" y="${y+17}" fill="#171719" font-size="${font}">${k.ratio.toFixed(1)}×</text>`});
 svg+='<text x="0" y="212" font-size="13" fill="#585858">attention 쌍의 수 / 224px 기준 · 선형 눈금</text>';q('#costChart').innerHTML=svg;
 q('#costReadout').textContent=`${res}px: ${c.tokens.toLocaleString()}² = ${c.pairs.toLocaleString()}개 관계 (${c.ratio.toFixed(1)}배). 실제 메모리와 시간은 attention 구현·하드웨어에 따라 다릅니다.`;
}
q('#resolution').onchange=updateTokens;updateTokens();
function updateEMA(){const m=Number(q('#momentum').value),r=M.emaExample(m),font=innerWidth<=650?21:16;q('#momentumValue').textContent=m.toFixed(3);let svg='';[0,.5,1,1.5].forEach(v=>{const y=209-v*115;svg+=`<line x1="44" y1="${y}" x2="525" y2="${y}" stroke="#EAEBEC"/><text x="0" y="${y+4}" font-size="${font}" fill="#585858">${v.toFixed(1)}</text>`});for(const [key,color]of[['student','#70737C'],['teacher','#F86825']])svg+=`<path d="${r[key].map((v,i)=>`${i?'L':'M'}${44+i*481/159},${209-v*115}`).join(' ')}" fill="none" stroke="${color}" stroke-width="${key==='teacher'?3:1.5}"/>`;svg+=`<text x="44" y="240" font-size="${font}" fill="#585858">0</text><text x="418" y="240" font-size="${font}" fill="#585858">160 steps</text>`;q('#emaChart').innerHTML=svg}
q('#momentum').oninput=updateEMA;updateEMA();
function color(v){const a=v<0?[96,150,213]:[248,104,37],base=[244,244,245],t=Math.min(1,Math.abs(v));return `rgb(${base.map((x,i)=>Math.round(x+(a[i]-x)*t)).join(',')})`}
function paintMatrix(id,m){const c=q(id),ctx=c.getContext('2d'),n=m.length,cell=c.width/n;ctx.clearRect(0,0,c.width,c.height);for(let i=0;i<n;i++)for(let j=0;j<n;j++){ctx.fillStyle=color(m[i][j]);ctx.fillRect(j*cell,i*cell,cell-.75,cell-.75)}}
function updateGram(){const d=Number(q('#distortion').value),a=Number(q('#anchor').value),rotate=q('#rotateFeatures').checked,r=M.gramExample(d,a,rotate);q('#distortionValue').textContent=d.toFixed(2);q('#anchorValue').textContent=a.toFixed(2);q('#gramLoss').textContent=r.loss.toFixed(5);paintMatrix('#gramTeacher',r.gt);paintMatrix('#gramStudent',r.gs);q('#gramTable').innerHTML='<caption>학생 Gram 행렬 · cosine · 행/열 = 패치 번호</caption><thead><tr><th scope="col">패치</th>'+r.gs.map((_,i)=>`<th scope="col">${i}</th>`).join('')+'</tr></thead><tbody>'+r.gs.map((row,i)=>`<tr><th scope="row">${i}</th>${row.map(v=>`<td>${v.toFixed(2)}</td>`).join('')}</tr>`).join('')+'</tbody>'}
q('#distortion').oninput=updateGram;q('#anchor').oninput=updateGram;q('#rotateFeatures').onchange=updateGram;updateGram();
function fmt(v){return(v>0?'+':'')+(v*100).toFixed(2)}
window.initReport=function(data){
function renderEffects(){
 const mobile=innerWidth<=650,x=v=>mobile?30+(v+10)/18*305:180+(v+10)/18*650;
 q('#effectChart').setAttribute('viewBox',mobile?'0 0 360 375':'0 0 1000 310');let svg='';
 [-10,-5,0,5].forEach(v=>{svg+=`<line x1="${x(v)}" y1="${mobile?37:15}" x2="${x(v)}" y2="${mobile?333:268}" stroke="${v===0?'#70737C':'#EAEBEC'}" stroke-dasharray="${v===0?'0':'3 5'}"/><text x="${x(v)}" y="${mobile?363:295}" font-size="15" text-anchor="middle" fill="#585858">${v>0?'+':''}${v}%p</text>`});
 data.lenses.forEach((l,i)=>{const y=mobile?53+i*85:44+i*66,m=l.effect.mean*100,lo=l.effect.ci95[0]*100,hi=l.effect.ci95[1]*100,c=m>=0?'#366351':'#CF1D21';svg+=`${mobile?`<rect x="0" y="${y-49}" width="360" height="33" fill="white"/>`:''}<text x="${mobile?10:0}" y="${mobile?y-25:y+5}" fill="#171719" font-size="17">${l.name}</text><line x1="${x(lo)}" y1="${y}" x2="${x(hi)}" y2="${y}" stroke="${c}" stroke-width="3"/><line x1="${x(lo)}" y1="${y-7}" x2="${x(lo)}" y2="${y+7}" stroke="${c}"/><line x1="${x(hi)}" y1="${y-7}" x2="${x(hi)}" y2="${y+7}" stroke="${c}"/><circle cx="${x(m)}" cy="${y}" r="6" fill="${c}"/><text x="${mobile?280:890}" y="${mobile?y-25:y+5}" fill="${c}" font-size="20" font-weight="600">${fmt(l.effect.mean)}</text>`});
 q('#effectChart').innerHTML=svg;
}renderEffects();window.addEventListener('resize',renderEffects);
function updateEffect(){const l=data.lenses.find(l=>l.key===q('#effectLens').value);q('#seedTable').innerHTML='<caption>H − class-matched random · %p</caption><thead><tr><th>선택 seed / 학습 seed</th><th>684162</th><th>88304</th><th>20260902</th></tr></thead><tbody>'+l.effect.matrix.map((row,i)=>`<tr><th scope="row">${i}</th>${row.map(v=>`<td style="color:${v>=0?'#366351':'#CF1D21'}">${fmt(v)}</td>`).join('')}</tr>`).join('')+'</tbody>';q('#absoluteBA').textContent=`평균 BA: H ${(l.absolute.h*100).toFixed(2)}% · 무작위 ${(l.absolute.random*100).toFixed(2)}% · 전체 데이터 ${(l.absolute.full*100).toFixed(2)}%. 95% 구간 [${fmt(l.effect.ci95[0])}, ${fmt(l.effect.ci95[1])}]%p.`}
q('#effectLens').onchange=updateEffect;updateEffect();q('#provenance').innerHTML=`<p>요약 SHA-256<br>${data.provenance.summary_sha256}<br>선택 SHA-256<br>${data.provenance.selection_sha256}</p>`+data.lenses.map(l=>`<p><strong>${l.name}</strong><br>${l.model_id}<br>revision: ${l.revision}<br>feature SHA-256: ${l.feature_sha256}</p>`).join('');
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const opts={signal:lifecycle.signal};const register=tool=>{try{Promise.resolve(context.registerTool(tool,opts)).catch(()=>{})}catch{}};register({name:'read_embedding_selection',title:'현재 임베딩 표본 읽기',description:'현재 보이는 렌즈, 표본, 고차원 cosine 이웃을 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){const l=lens();return{lens:state.lens,sample:state.sample,neighbors:l.neighbors[state.sample],cosines:l.similarities[state.sample]}}});register({name:'configure_embedding_view',title:'임베딩 표본과 렌즈 선택',description:'화면과 같은 선택 동작으로 렌즈와 표본을 변경합니다. 모델 실행이나 데이터 변경은 하지 않습니다.',inputSchema:{type:'object',properties:{lens:{type:'string',enum:data.lenses.map(l=>l.key)},sample:{type:'integer',minimum:0,maximum:299}},required:['lens','sample'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||!data.lenses.some(l=>l.key===input.lens)||!Number.isInteger(input.sample)||input.sample<0||input.sample>299||Object.keys(input).some(k=>!['lens','sample'].includes(k)))throw new Error('Valid lens and sample 0–299 required');selectLens(input.lens);selectSample(input.sample);return{lens:state.lens,sample:state.sample}}})}
};
window.addEventListener('resize',()=>{updateTokens();updateEMA()});
})();
